# Cmd IDs and Response IDs. Autogenerated from header file 
# in CmdResponseDefinitions.h 

ORIENTATION_CMD_REJECT = 0xA506
RESPONSE_SIGNAL = 0xB501
ORIENTATION_CMD_ACCEPT = 0xA505
CTRL_ACTIVE = 0xA501


