# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm_packet.proto',
  package='',
  serialized_pb=_b('\n\x11\x63omm_packet.proto\"4\n\x12\x43ommandOrientation\x12\r\n\x05\x41ngle\x18\x01 \x02(\x02\x12\x0f\n\x07Heading\x18\x02 \x02(\x02\"-\n\x10IdValuePairFloat\x12\n\n\x02Id\x18\x01 \x02(\r\x12\r\n\x05Value\x18\x02 \x01(\x02\"c\n\rCommandPacket\x12\x31\n\x14\x43ommandedOrientation\x18\x01 \x01(\x0b\x32\x13.CommandOrientation\x12\x1f\n\x04\x43mds\x18\x02 \x03(\x0b\x32\x11.IdValuePairFloat\"d\n\x0fTelemetryPacket\x12\x15\n\rMeasuredAngle\x18\x01 \x02(\x02\x12\x17\n\x0fMeasuredHeading\x18\x02 \x02(\x02\x12!\n\x06Status\x18\x03 \x03(\x0b\x32\x11.IdValuePairFloat')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMANDORIENTATION = _descriptor.Descriptor(
  name='CommandOrientation',
  full_name='CommandOrientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Angle', full_name='CommandOrientation.Angle', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Heading', full_name='CommandOrientation.Heading', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=73,
)


_IDVALUEPAIRFLOAT = _descriptor.Descriptor(
  name='IdValuePairFloat',
  full_name='IdValuePairFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='IdValuePairFloat.Id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='IdValuePairFloat.Value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=120,
)


_COMMANDPACKET = _descriptor.Descriptor(
  name='CommandPacket',
  full_name='CommandPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CommandedOrientation', full_name='CommandPacket.CommandedOrientation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Cmds', full_name='CommandPacket.Cmds', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=221,
)


_TELEMETRYPACKET = _descriptor.Descriptor(
  name='TelemetryPacket',
  full_name='TelemetryPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MeasuredAngle', full_name='TelemetryPacket.MeasuredAngle', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MeasuredHeading', full_name='TelemetryPacket.MeasuredHeading', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Status', full_name='TelemetryPacket.Status', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=323,
)

_COMMANDPACKET.fields_by_name['CommandedOrientation'].message_type = _COMMANDORIENTATION
_COMMANDPACKET.fields_by_name['Cmds'].message_type = _IDVALUEPAIRFLOAT
_TELEMETRYPACKET.fields_by_name['Status'].message_type = _IDVALUEPAIRFLOAT
DESCRIPTOR.message_types_by_name['CommandOrientation'] = _COMMANDORIENTATION
DESCRIPTOR.message_types_by_name['IdValuePairFloat'] = _IDVALUEPAIRFLOAT
DESCRIPTOR.message_types_by_name['CommandPacket'] = _COMMANDPACKET
DESCRIPTOR.message_types_by_name['TelemetryPacket'] = _TELEMETRYPACKET

CommandOrientation = _reflection.GeneratedProtocolMessageType('CommandOrientation', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDORIENTATION,
  __module__ = 'comm_packet_pb2'
  # @@protoc_insertion_point(class_scope:CommandOrientation)
  ))
_sym_db.RegisterMessage(CommandOrientation)

IdValuePairFloat = _reflection.GeneratedProtocolMessageType('IdValuePairFloat', (_message.Message,), dict(
  DESCRIPTOR = _IDVALUEPAIRFLOAT,
  __module__ = 'comm_packet_pb2'
  # @@protoc_insertion_point(class_scope:IdValuePairFloat)
  ))
_sym_db.RegisterMessage(IdValuePairFloat)

CommandPacket = _reflection.GeneratedProtocolMessageType('CommandPacket', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDPACKET,
  __module__ = 'comm_packet_pb2'
  # @@protoc_insertion_point(class_scope:CommandPacket)
  ))
_sym_db.RegisterMessage(CommandPacket)

TelemetryPacket = _reflection.GeneratedProtocolMessageType('TelemetryPacket', (_message.Message,), dict(
  DESCRIPTOR = _TELEMETRYPACKET,
  __module__ = 'comm_packet_pb2'
  # @@protoc_insertion_point(class_scope:TelemetryPacket)
  ))
_sym_db.RegisterMessage(TelemetryPacket)


# @@protoc_insertion_point(module_scope)
